fort-nix/nix-bitcoin

- README.md
Updated Debian 9 Stretch Tutorial
>  Add Debian 9 Stretch Tutorial to README.md 

- modules/clightning.nix
- modules/electrs.nix
- modules/nix-bitcoin.nix
- nix-bitcoin.nix
- pkgs/electrs.nix
This PR corrects an erroneous description of the clightning data directory in the clightning.nix module, adds the electrs package, and adds the electrs module.
> Minor corrections, electrs package, electrs module

- README.md
Potentially we could make this a Wiki entry along with the VirtualBox guide overworked to fit this tutorial's numbered-step format.
> Add own hardware tutorial to README.md

- README.md
- modules/bitcoind.nix
- pkgs/banlist.sh
Otherwise it'll take a couple of seconds to wait for every addban RPC to time out. CC @nixbitcoin
> Import bitcoind banlist in separate service

- modules/bitcoind.nix
> fix making banlist importer wait for bitcoind to start up

- README.md
- modules/nix-bitcoin.nix
- modules/spark-wallet.nix
> Fix spark wallet QR code display

- README.md
This is a first step in more extensive documentation of this project. Eventually the documentation in the README should be split up into an INSTALL.md, USEAGE.md, and FAQ.md. I think a good time to do this would be after we move user configuration functionality from modules/nix-bitcoin.nix to configuration.nix.
> Document connecting to ssh Tor Hidden Service

- modules/nix-bitcoin.nix
- network.nix
Without this PR, disabling clightning does not work.
> Stop assuming that clightning is always enabled

- README.md
- docs/faq.md
- docs/install.md
- docs/usage.md
This PR slims down README.md and moves its content to an install.md and a useage.md in a docs directory. Overall documentation is brought to a common format and enhanced. The documentation replaces profiles with the new model in https://github.com/jonasnick/nix-bitcoin/pull/29, so it only really makes sense in conjunction with that.
> Split up and enhance documentation

- docs/install.md
Incorporate @0xB10C "Feedback and minor improvements"
Closes #49
> Improve install documentation

- configuration.nix
- default.nix
- modules/hardware-wallets.nix
- modules/nix-bitcoin.nix
- pkgs/hwi/default.nix
> Add support for ledger and trezor with bitcoin-core/HWI

- docs/install.md
Added the instructions to run nix-bitcoin with virtualbox on a macOS host.
I'll rebase this on top of master when #82 is merged.
> macOS installation instructions

- README.md
Update tested hardware with reports from https://github.com/fort-nix/nix-bitcoin/issues/39
> Update tested hardware

- modules/electrs.nix
This PR fixes #86 by placing startscript in a systemd RuntimeDirectory only accessible by the electrs user as per @jonasnick's suggestion. It also sets a cfg.user and cfg.group variable and removes the hardcoded electrs user and group in several places.
I'm a bit concerned that I can't pass `${RuntimeDirectory}` from `serviceConfig` to `preStart` and had to hardcode `/run/electrs/startscript.sh`, but I've seen this done in other nix modules upstream. Will this be an issue?
Closes #93
> Move electrs startscript to tempdir and fix nits

- default.nix
- pkgs/pylightning/default.nix
Allows to add clightning plugins in the future (or in private forks).
> Add pylightning package

- modules/liquid.nix
> Fix liquid data directory permission

- default.nix
- modules/nix-bitcoin.nix
- pkgs/liquid-swap/default.nix
Fixes #103. ~~Blocked at least until https://github.com/Blockstream/liquid-swap/issues/2 is resolved.~~
> Liquid swap tool

- README.md
- modules/clightning.nix
- modules/nix-bitcoin-services.nix
> Simplify clightning preStart

- default.nix
- pkgs/elementsd/default.nix
Because `LC_ALL` must be set to make the tests work (https://github.com/bitcoin/bitcoin/issues/14948#issuecomment-447049325) I also copied the rest from the current nixpkgs bitcoind package.
> Update elementsd to 0.18.1.1

- modules/bitcoind.nix
- modules/nix-bitcoin.nix
... which is a better place for this. CC @cypherpunk2140
> Move zmq options from nix-bitcoin.nix to bitcoind module

- docs/install.md
- network/network-vbox.nix
This eliminates the manual resize step in vbox deployment
> Set default size of the virtualbox machine disk

- .travis.yml
- pkgs/default.nix
It's helpful to be able to use these packages when importing nix-bitcoin. Opened a PR separately from #136 because that allows experimentation with the idea before adjusting the docs and everything.
> Add nixops19_09 to default pkgs.

- docs/faq.md
I had a problem with low system entropy. I want to document this to spare people the troubleshooting.
> Document low-entropy problem

- pkgs/spark-wallet/generate.sh
- pkgs/spark-wallet/node-packages.nix
- pkgs/spark-wallet/pkg.json
I updated spark-wallet to 0.2.14 and changed it to fetch spark-wallet sources from GitHub, so we can verify @shesek's signature. To replicate run `generate.sh`.
> Update spark-wallet 0.2.13 -> 0.2.14

- examples/deploy-container.sh
- examples/deploy-nixops.sh
- examples/deploy-qemu-vm.sh
- examples/start-bash-session.sh
Previously, the sessions contained only explicitly exported variables and functions.
This was fragile and in part buggy due to lacking exports.
Interactive features like user-defined aliases and functions are still working as before.
> examples: execute bash sessions in script environment

- modules/bitcoind.nix
https://github.com/ElementsProject/lightning/pull/3565 added a timeout if the Bitcoin plugin never completes the handshake, instead of waiting indefinitely for bitcoind to come up like before.
Because the `ExecStartPost` runs concurrently to the `ExecStart`, the systemd service doesn't fail when `ExecStart` fails on the aforementioned clightning timeout. Instead, systemd times out the `ExecStartPost` itself and shuts down the whole service gracefully, preventing `Restart=on-failure` from restarting the service.
This situation can also be alleviated by 
```
TimeoutStartFailureMode = "kill";
```
However, this leads to the equally unwanted result that dependent services like spark-wallet don't restart when clightning restarts successfully (https://github.com/systemd/systemd/issues/1312). …
> bitcoind: postStart wait until bitcoind can receive rpc calls

- examples/configuration.nix
- modules/bitcoind.nix
- modules/clightning.nix
- modules/lnd.nix
- modules/modules.nix
- modules/netns-isolation.nix
- modules/presets/secure-node.nix
- test/scenarios/default.py
- test/scenarios/lib.py
- test/scenarios/withnetns.py
- test/test.nix
This PR allows LND and c-lightning to run side-by-side in tests and deployments.
> Concurrent LN

- pkgs/generate-secrets/default.nix
- pkgs/generate-secrets/generate-secrets.sh
> generate-secrets: always run with Bash, stop on errors

- pkgs/lightning-loop/default.nix
- pkgs/lightning-loop/get-sha256.sh
This PR updates lightning-loop.
@Guggero now also signs releases.
> lightning-loop: 0.11.0-beta -> 0.11.1-beta

- pkgs/electrs/default.nix
> electrs: 0.8.5 -> 0.8.6

- pkgs/lightning-loop/default.nix
Simple update of lightning-loop allowing you to set custom swap size limits.
> lightning-loop: 0.11.1-beta -> 0.11.2-beta

- modules/clightning-plugins/clboss.nix
- modules/clightning-plugins/default.nix
- modules/modules.nix
- pkgs/clboss/default.nix
- pkgs/default.nix
- test/tests.nix
Adds @ZmnSCPxj's CLBOSS.
- Loaded via our clightning plugins mechanism
- Networked over tor with custom torify
- No PGP signatures available.
Closes https://github.com/fort-nix/nix-bitcoin/issues/273
> Add CLBOSS

- README.md
- examples/configuration.nix
- modules/joinmarket-ob-watcher.nix
- modules/modules.nix
- modules/netns-isolation.nix
- modules/nodeinfo.nix
- modules/onion-services.nix
- modules/presets/enable-tor.nix
- pkgs/joinmarket/default.nix
- pkgs/joinmarket/get-sha256.sh
- test/tests.nix
- test/tests.py
This PR adds the obwatcher script to the joinmarket package and adds a stand-alone joinmarket-obwatcher module.
I decided to make this module independent from the joinmarket module following the principle of least principle. It does not need to interact in anyway with the existing bitcoind or joinmarket services.
> JoinMarket Orderbook Watcher

- README.md
- ci/build-to-cachix.sh
- examples/deploy-container.sh
- examples/deploy-nixops.sh
- examples/deploy-qemu-vm.sh
- modules/backups.nix
- modules/bitcoind-rpc-public-whitelist.nix
- modules/bitcoind.nix
- modules/btcpayserver.nix
- modules/clightning.nix
- modules/electrs.nix
- modules/hardware-wallets.nix
- modules/joinmarket-ob-watcher.nix
- modules/joinmarket.nix
- modules/lightning-loop.nix
- modules/liquid.nix
- modules/lnd.nix
- modules/netns-isolation.nix
- modules/recurring-donations.nix
- modules/spark-wallet.nix
- pkgs/elementsd/default.nix
- pkgs/lib.nix
- pkgs/python-packages/chromalog/default.nix
- test/lib/copy-src.sh
- test/run-tests.sh
Some (mostly minor) refactorings and cleanups that I had piled up over the recent months.
To review commit `services: use consistent layout`, run `test/run-tests.sh eval` on this commit and its parent to see that the system derivation is unchanged.
> Refactorings, cleanups

- docs/usage.md
- modules/joinmarket.nix
- pkgs/joinmarket/default.nix
- pkgs/joinmarket/get-sha256.sh
- test/tests.nix
- Update joinmarket package
- Revert unofficial release settings
- Move Yield Generator config to configFile
- Add new config option max_sweep_fee_change
> joinmarket: 0.8.0-a5e8879 -> 0.8.1

- modules/presets/secure-node.nix
Closes https://github.com/fort-nix/nix-bitcoin/issues/328
> bitcoind: secure-node remove assumevalid

- modules/electrs.nix
- pkgs/electrs/default.nix
Closes https://github.com/fort-nix/nix-bitcoin/issues/330
> electrs: v0.8.7 -> v0.8.8

- modules/joinmarket.nix
- pkgs/joinmarket/default.nix
- pkgs/python-packages/default.nix
- pkgs/python-packages/jmbase/default.nix
- pkgs/python-packages/jmdaemon/default.nix
Urgent security update, see [release notes](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/release-notes/release-notes-0.8.2.md)
> joinmarket: 0.8.1 -> 0.8.2

- pkgs/electrs/default.nix
Closes https://github.com/fort-nix/nix-bitcoin/issues/343
> electrs: 0.8.8 -> 0.8.9

- examples/README.md
- test/lib/make-test.nix
- test/run-tests.sh
Used by https://github.com/fort-nix/nixbitcoin.org
> run-tests: add 'vm' command

- pkgs/clightning-plugins/default.nix
- pkgs/default.nix
- pkgs/nixpkgs-pinned.nix
- pkgs/python-packages/cryptography/default.nix
- pkgs/python-packages/cryptography/vectors.nix
- pkgs/python-packages/default.nix
- pkgs/python-packages/pylightning/default.nix
- pkgs/python-packages/pyln-client/default.nix
- pkgs/python-packages/pyln-proto/default.nix
- pkgs/python-packages/recommonmark/default.nix
Includes
- btcpayserver: 1.0.7.0 -> 1.0.7.2
- clightning: 0.9.3 -> 0.10.0
Had to pin cryptography to exactly version 3.3.2
Also, update clightning-plugins
> Update nixos unstable

- README.md
> README: switch IRC network from freenode to libera

- examples/configuration.nix
- modules/joinmarket-ob-watcher.nix
- modules/joinmarket.nix
- modules/versioning.nix
- pkgs/joinmarket/default.nix
- pkgs/python-packages/coincurve/default.nix
Update JoinMarket. See commit message for notes.
> joinmarket: 0.8.2 -> 0.8.3

- examples/README.md
- examples/configuration.nix
- examples/minimal-configuration.nix
- modules/backups.nix
- modules/bitcoind.nix
- modules/clightning.nix
- modules/joinmarket-ob-watcher.nix
- modules/joinmarket.nix
- modules/liquid.nix
- modules/lnd.nix
- modules/modules.nix
- modules/nix-bitcoin.nix
- modules/nodeinfo.nix
- modules/recurring-donations.nix
- modules/secrets/secrets.nix
- modules/versioning.nix
- pkgs/lib.nix
- test/run-tests.sh
Mostly minor cleanups and refactorings that have piled up recently.
The only major functional change is in `backups: backup NixOS uid, gid mappings`.
> Misc. improvements

- pkgs/joinmarket/default.nix
> joinmarket: Update patch hash

- docs/install.md
- docs/usage.md
- examples/shell.nix
- helper/fetch-release
- helper/makeShell.nix
We should include this in the next release.
> Shell improvements

- examples/README.md
- helper/makeShell.nix
extra-container is not supported on these systems.
Fixes #398
> examples: Fix shell on non-Linux systems

- modules/joinmarket.nix
Fixes https://github.com/fort-nix/nix-bitcoin/issues/439
Does this solve your issue @alumbigi?
> joinmarket: fix fidelity bond default values

- modules/lnd.nix
- Use systemd startup notification.
- Use new option `--wallet-unlock-password-file` instead of manual unlocking.
@Kixunil, this is also relevant for cryptoanarchy-deb-repo-builder.
> lnd: improve service initialization

- README.md
- modules/clightning-plugins/commando.nix
- modules/clightning-plugins/default.nix
- pkgs/clightning-plugins/default.nix
- pkgs/python-packages/default.nix
- pkgs/python-packages/pyln-proto/default.nix
- pkgs/python-packages/runes/default.nix
- pkgs/python-packages/sha256/default.nix
- test/tests.nix
commando is a clightning plugin that allows you to perform clightning RPC over the lightning network itself
> clightning-plugins: add commando plugin

- modules/backups.nix
Refactor fullIfOlderThan and expose cleanup.maxFull option.
> backups: bring in line with upstream duplicity

- README.md
- SECURITY.md
Closes https://github.com/fort-nix/nix-bitcoin/issues/455
> Add nix-bitcoin security fund information

- modules/lnd.nix
- pkgs/default.nix
- pkgs/lndinit/default.nix
- pkgs/lndinit/get-sha256.sh
> lnd: Use `lndinit` for wallet creation

- modules/lightning-loop.nix
- modules/lnd.nix
- pkgs/lib.nix
- test/tests.nix
- test/tests.py
This is useful for non-local access to the lnd REST server.
@sputn1ck, does this fit your use case?
> lnd, lightning-loop: add certificate options `extraIPs` and `extraDomains`

- README.md
- docs/hardware.md
- examples/configuration.nix
- examples/deploy-krops.sh
- examples/qemu-vm/minimal-vm.nix
- modules/bitcoind-rpc-public-whitelist.nix
- modules/fulcrum.nix
- modules/modules.nix
- modules/netns-isolation.nix
- modules/nodeinfo.nix
- modules/presets/enable-tor.nix
- pkgs/pinned.nix
- test/lib/make-test.nix
- test/tests.nix
- test/tests.py
Fulcrum has been [confirmed to be stable](https://github.com/fort-nix/nix-bitcoin/pull/456#issuecomment-1173165473), so we can now add it.
This PR is based on https://github.com/fort-nix/nix-bitcoin/pull/508 (`More NixOS 22.05 fixes`).
> Add fulcrum module

- README.md
- SECURITY.md
- Add to README
- Improve wording
> docs: improve `Security Fund` documentation

- docs/img/LICENSE
I've used the attribution scheme recommend [here](https://wiki.creativecommons.org/wiki/best_practices_for_attribution) (section "This is a good attribution for material from which you created a derivative work").
> img/logo: add LICENSE

- examples/qemu-vm/minimal-vm.nix
- modules/joinmarket.nix
- modules/onion-addresses.nix
- modules/secrets/secrets.nix
- modules/spark-wallet.nix
- pkgs/clightning-plugins/default.nix
- pkgs/clightning-rest/default.nix
- pkgs/joinmarket/default.nix
- pkgs/netns-exec/default.nix
- pkgs/nixops/default.nix
- pkgs/python-packages/specific-versions/autobahn.nix
- pkgs/rtl/default.nix
- test/lib/make-test.nix
- test/lib/shellcheck-services.nix
- test/lib/test-lib.nix
- test/shellcheck.sh
- test/tests.nix
- Fixes #528 
- https://github.com/NixOS/nixpkgs/pull/189836
> ShellCheck on scripts generated by nix

- pkgs/default.nix
- pkgs/lnd-0.15.2.nix
- pkgs/pinned.nix
Includes an emergency hotfix:
https://github.com/lightningnetwork/lnd/releases/tag/v0.15.2-beta
> pkgs: add lnd 0.15.2

- pkgs/default.nix
- pkgs/lnd-0.15.4.nix
- pkgs/pinned.nix
Includes an emergency hotfix:
https://github.com/lightningnetwork/lnd/releases/tag/v0.15.4-beta
> pkgs: add lnd 0.15.4 (hotfix)

- pkgs/clightning-plugins/default.nix
Check this with
```bash
diff -u --color \
$(nix build --no-link --print-out-paths github:fort-nix/nix-bitcoin?ref=v0.0.92#clightning-plugins/prometheus) \
$(nix build --no-link --print-out-paths .#clightning-plugins/prometheus)
```
> clightning-plugins/prometheus: fix patch not being applied

- modules/versioning.nix
This was brought up by a user via Matrix.
> versioning: improve `configVersion` description

- pkgs/clightning-rest/default.nix
- pkgs/clightning-rest/generate.sh
https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.4
> clightning-rest: 0.10.3 -> 0.10.4

- modules/clightning-plugins/clboss.nix
- modules/obsolete-options.nix
- pkgs/clboss/default.nix
- test/tests.nix
Running live on nixbitcoin.org.
> clboss: 0.13A -> 0.13

- pkgs/bitcoin/default.nix
Backport of https://github.com/NixOS/nixpkgs/pull/256091
> bitcoin: add shell completions

- dev/README.md
- examples/flakes/flake.nix
Add some improvements in response to a user question from Matrix.
> examples/flake.nix: minor improvements

- test/README.md
This was reported by a Matrix user.
> test/README: mention Flakes requirement

- pkgs/default.nix
- pkgs/nbxplorer/default.nix
- pkgs/nbxplorer/deps.json
- pkgs/pinned.nix
Hotfix backport of https://github.com/NixOS/nixpkgs/pull/407336
Fixes https://github.com/MetacoSA/NBitcoin/pull/1269
Edit: Channel status of NixOS/nixpkgs#407336: https://nixpk.gs/pr-tracker.html?pr=407336
> nbxplorer: init at 2.5.26

- modules/clightning-plugins/clnrest.nix
> clightning: set service as active only after clnrest has started

- pkgs/rtl/default.nix
- pkgs/rtl/generate.sh
https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.5
> rtl: 0.15.4 -> 0.15.5
