modules/clightning.nix
modules/nix-bitcoin.nix

Sets a Tor proxy for all outgoing clightning connections, which allows users to connect to other .onion Lightning nodes. Forces clightning to always use Tor proxy. Binds clightning to Tor HS at 127.0.0.1:9735

Tor proxy, always-use-proxy, bind to localhost clightning

---

modules/nix-bitcoin.nix
pkgs/nodeinfo.sh

This commit adds Tor support to liquidd. Should it include the external ip option to advertise the hidden service for inbound connections?

Add proxy and hidden service to liquidd

---

modules/bitcoind.nix
modules/electrs.nix
modules/nix-bitcoin.nix
pkgs/electrs.nix
pkgs/nodeinfo.sh

This commit fixes electrs, reenables it, adds an electrs Tor v3 HS so users can connect from the outside, and a high-memory option. 
The high-memory option allows users with high-memory (< 8 GB RAM) to sync faster. How should this be documented?

Fix electrs and add electrs hidden service

---

README.md
modules/electrs.nix
modules/nix-bitcoin.nix

Right now I prefer to not use electrs with the "all" profile because I'm using the "all" profile now on my machine and I don't want electrs. Imo as long as it is documented in the README  how to turn it on that's okay.
cc @nixbitcoin

Some fixes to electrs server

---

network-libvirtd.nix

Example deployment for libvirtd.
FYI: 4GB of ram doesn't seem to be enough for bitcoind to sync.

Add network-libvirtd.nix for libvirtd environments.

---

modules/electrs.nix
modules/nix-bitcoin.nix
pkgs/electrs/default.nix

@romanz has enabled rust stable upstream. This commit transitions electrs from rust nightly to rust stable 1.31. It also updates the electrs version to 0.5.0. I also specified the electrum-rpc-addr to make the hidden service at port 50001 more reliable.

Use rust stableinstead of nightly, update electrs, specify electrum-rpc-addr

---

configuration.nix
modules/nix-bitcoin.nix

This PR seeks to give the user more granular control over which modules he wants to run on his nix-bitcoin node. Above each option the user will find documentation explaining what the module is and when to enable/disable it.
Tested on top of 1efe510 and f0b78ee

Remove profiles and replace with options to enable/disable each module separately in configuration.nix

---

README.md
configuration.nix
modules/default.nix
modules/nix-bitcoin.nix
modules/recurring-donations.nix

Allows to send tallyco.in donations in given intervals with clightning by adding something like this to your `configuration.nix`:
```
services.recurring-donations.enable = true;
services.recurring-donations.tallycoin = {
"djbooth007" = 1000;
"hillebrandmax" = 1000;
};
```

Add recurring donations module

---

docs/usage.md
modules/electrs.nix
modules/nix-bitcoin.nix
network/network.nix
secrets/generate_secrets.sh
shell.nix

This PR modifies electrs to use a self-signed ssl certificate to provide additional connection security. This is vital for the Electrum Android App and should align connecting to electrs with standard Electrum usage.
Relevant Issue: https://github.com/jonasnick/nix-bitcoin/issues/33

electrs ssl

---

pkgs/nixpkgs-pinned.nix

Notable change: includes bitcoind version bump to 0.18
fixes #60

Update nixpkgs and switch from nixpkgs-unstable to nixos-unstable. 

---

modules/clightning.nix
modules/nix-bitcoin-pkgs.nix
modules/nix-bitcoin.nix

Without this PR nix-bitcoin installs multiple versions of bitcoind and one of them is with GUI. To get rid of GUI bitcoin with this PR, run `nixops deploy`, reboot and run `nix-collect-garbage -d` on your target.

Fix package dependencies

---

docs/usage.md

I noticed that we were missing specific instructions on how to connect through Orbot, which might be a problem for novice users.

More detailed instructions on connecting to spark-wallet and electrs through Tor

---

contrib/vbox-resize-disk1.sh
docs/install.md

It turns out that 300gb is not enough as electrs consumes ~50gb as well. 
```
$ du -sh /var/lib/*
248G	/var/lib/bitcoind
60M	/var/lib/clightning
48G	/var/lib/electrs
20K	/var/lib/nixos
44K	/var/lib/onion-chef
12K	/var/lib/private
156K	/var/lib/systemd
6.7M	/var/lib/tor
4.0K	/var/lib/udisks2
```
PR also contains some typo fixes.

bump vbox default disk size to 350gb

---

modules/bitcoind.nix
modules/liquid.nix

This allows using an existing datadir, for which the user may not have permissions, f.e. an external drive. CC @stevenroose

Always chown bitcoin/liquid data directories

---

modules/liquid.nix
modules/nix-bitcoin.nix

Closes https://github.com/fort-nix/nix-bitcoin/issues/84
I've made `validatepegin` false-by-default in configuration.nix. Should it be an opt-out? Is setting the option in liquid.conf even necessary? Seems to be enabled by default according to https://github.com/ElementsProject/elements/blob/master/share/examples/liquid.conf "# Validate pegin claims. All functionaries must run this. (default: 1)" @stevenroose

Enable validatepegin for Liquid

---

pkgs/electrs/default.nix

New and better version of https://github.com/fort-nix/nix-bitcoin/pull/97 now that @romanz updated the crate.
@jb55 can you test deploying electrs and verify electrs sha256.

Update electrs to v0.7.1

---

.travis.yml
pkgs/nixpkgs-pinned.nix

This builds everything to make sure everything works on either the latest release or unstable branch. In the future we could do more interesting nixops builds to test modules, but for now we just nix-build everything and make sure it compiles.
We test the build with two different versions of nixpkgs:
- nixpkgs-channels/nixos-19.03
- nixpkgs-channels/nixos-unstable

Add travis ci builds

---

pkgs/nixops/default.nix
pkgs/nixops/release.nix.patch
shell.nix

Without this, starting the virtualbox guest service fails during machine activation.
This is due to an incompatible NixOS machine base image.
Fix this by using an updated version of nixops.
I've already reported [this issue](https://github.com/NixOS/nixops/issues/1207) upstream.
@jonasnick, could you check if this new nixops version works
correctly for your non-virtualbox deployments?

Fix virtualbox deployment for 19.09

---

pkgs/nixops/release.nix.patch

Otherwise nix-shell doesn't start up:
```
building '/nix/store/c03b0sb0b822m7n1j0rhg8bfbmqv2vv2-src.drv'...
patching file release.nix
Hunk #3 FAILED at 83.
1 out of 3 hunks FAILED -- saving rejects to file release.nix.rej
builder for '/nix/store/c03b0sb0b822m7n1j0rhg8bfbmqv2vv2-src.drv' failed with exit code 1
error: build of '/nix/store/c03b0sb0b822m7n1j0rhg8bfbmqv2vv2-src.drv' failed
(use '--show-trace' to show detailed location information)
```
CC @erikarvstedt

Fix release.nix.patch for our nixops

---

modules/secrets/generate-secrets.nix
modules/secrets/secrets.nix

See commit msgs.
We didn't catch this error because `nix-bitcoin.nix` sets the secrets dir to `/secrets` (default is `/etc/nix-bitcoin-secrets`).

Fix secrets setup

---

test/make-test.nix

this may also be fixed by disabling `vmx` (see [here](https://www.mail-archive.com/qemu-devel@nongnu.org/msg665051.html)),
but it's safer to just return to the old working QEMU version.

fix qemu error on travis

---

examples/configuration.nix
modules/bitcoind.nix
modules/clightning.nix
modules/default.nix
modules/electrs.nix
modules/hardware-wallets.nix
modules/lightning-charge.nix
modules/liquid.nix
modules/lnd.nix
modules/nanopos.nix
modules/nix-bitcoin.nix
modules/presets/secure-node.nix
modules/spark-wallet.nix
test/test.nix

Note that all commits up to and including `extract variable 'cfg'` are pure refactorings without any effects on evaluation results.
You can verify this with [this helper script](https://gist.github.com/5b0b1a7787ebc1342fcc3f237da5afa7), which compares the VM test derivation of the current worktree to the one in master.
Copy it to the repo root and use it like this:
```
git checkout ab61794 # commit 'extract variable 'cfg'
./diff-vm-drv.sh
git checkout 6c22e13 # commit 'copy-root-authorized-keys: use inline script definition'
./diff-vm-drv.sh
```

Rename nix-bitcoin.nix to presets/secure-node.nix

---

pkgs/pinned.nix

It appears the pinned attrset is a bit adhoc. This generalizes
pinned.nix so that you can do:
$ nix build -f . pinned.stable.hwi
$ nix build -f . pinned.unstable.hwi

Make it easy to use pinned packages

---

examples/configuration.nix
modules/presets/secure-node.nix
pkgs/generate-secrets/generate-secrets.sh

AFAIK electrs only needs sysperms when it is not getting blocks over jsonrpc, i.e. cfg.high-memory.
I also removed the St. Kitts and Nevis country-code. It was initially a joke, but I think it's unnecessary and could be used to fingerprint nix-bitcoin users. More feedback on the fingerprinting of TLS certs welcome.

Electrs fixes

---

modules/bitcoind.nix
modules/clightning.nix
modules/electrs.nix
modules/liquid.nix
modules/lnd.nix

Closes https://github.com/fort-nix/nix-bitcoin/issues/53
Combined with the fact that AFAICT you can't login with `bitcoin`, `clightning`, `electrs`, `liquid` users, this should completely eliminate the possibility of an attacker placing something similar to a `.bashrc` file into the users home which is then executed every time the user logs in.
For example:
```console
[root@nix-bitcoin:/var/lib]# sudo -u bitcoin printenv
LANG=en_US.UTF-8
TERMINFO_DIRS=/root/.nix-profile/share/terminfo:/etc/profiles/per-user/root/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo
TERM=xterm-256color
PATH=/root/bin:/run/wrappers/bin:/root/.nix-profile/bin:/etc/profiles/per-user/root/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin …
```

Remove bitcoin, clightning, electrs, liquid user home directory

---

pkgs/electrs/default.nix
pkgs/electrs/get-sha256.sh
pkgs/nixpkgs-pinned.nix

This PR changes the electrs expression to fetch sources from the releases archive with `fetchurl` instead of `fetchFromGitHub`. This allows us to calculate the sha256 ahead of time and compare it with Roman Zeyde's gpg-signed git tags. I have provided a helper script to automate the process.
Overall this should improve expression integrity, and I plan to implement this for all our packages where gpg verification is possible.

Get electrs source tarball with gpg verified sha256 and corresponding helper script

---

modules/lnd.nix

I've got a slightly contrived setup where I'm running nix-bitcoin in a container that shares network ports with another container which also uses 8080 and it's harder to change than in lnd ...

lnd: add option for configuring REST port

---

.travis.yml
pkgs/electrs/default.nix

* Add a 'blocks_dir' option
* Return fee for unconfirmed transactions history (for Electrum 4.0)
* Handle SIGUSR1 for external notifications
* Update to latest rust-bitcoin
* Fix deadlock and refactor RPC threading

electrs: 0.8.3 -> 0.8.5

---

pkgs/elementsd/default.nix
pkgs/elementsd/get-sha256.sh
pkgs/hwi/default.nix
pkgs/hwi/hidapi/default.nix
pkgs/nixpkgs-pinned.nix

This PR updates nixpkgs (unstable rev includes bitcoind 0.20.0) and elementsd. It also adds an elementsd `get-sha256.sh` to easily determine verified sha256 sums for updates.

Update: nixpkgs and elementsd

---

.travis.yml
examples/configuration.nix
modules/bitcoind.nix
modules/clightning.nix
modules/electrs.nix
modules/lightning-charge.nix
modules/liquid.nix
modules/lnd.nix
modules/modules.nix
modules/nanopos.nix
modules/netns-isolation.nix
modules/nix-bitcoin-services.nix
modules/nix-bitcoin-webindex.nix
modules/presets/secure-node.nix
modules/recurring-donations.nix
modules/spark-wallet.nix
pkgs/default.nix
pkgs/generate-secrets/openssl.cnf
pkgs/netns-exec/default.nix
pkgs/netns-exec/src/Makefile
pkgs/netns-exec/src/main.c
test/run-tests.sh
test/scenarios/default.py
test/scenarios/lib.py
test/scenarios/withnetns.py
test/test-script.py
test/test.nix

Network Namespaces are a significant security improvement, mitigating the bind race leak security vulnerability and unnecessary communications between nix-bitcoin services. Network namespaces round-off our service isolation to cover all levels of inter-service interaction.
Special thank you to @erikarvstedt for generalizing the `makeNetnsServices` :rocket:

Network Namespaces

---

docs/usage.md
modules/electrs.nix
modules/netns-isolation.nix
modules/presets/secure-node.nix
pkgs/generate-secrets/generate-secrets.sh
pkgs/generate-secrets/update-secrets.sh
test/scenarios/default.py
test/scenarios/withnetns.py

This PR removes the electrs tls proxy and its associated complexity. In the future we can allow all kinds of networking with the solution described in https://github.com/fort-nix/nix-bitcoin/issues/193#issuecomment-654174562

Remove electrs tls

---

modules/dbus.nix
modules/modules.nix
modules/presets/secure-node.nix
test/scenarios/default.py
test/scenarios/withnetns.py

Mitigates a security issue that allows unprivileged users to read other unprivileged user's processes' credentials from CGroup using `systemctl status`. Also adds tests to make sure this issue doesn't reoccur.

Fix systemd leak

---

modules/bitcoind.nix
modules/clightning.nix
modules/electrs.nix
modules/liquid.nix
modules/lnd.nix
modules/presets/secure-node.nix
pkgs/generate-secrets/default.nix
pkgs/generate-secrets/generate-secrets.sh
pkgs/generate-secrets/rpcauth/rpcauth.py
test/scenarios/default.py
test/scenarios/withnetns.py

This PR changes bitcoind rpc authentication to the `rpcauth` feature with HMAC-SHA-256 hashed passwords. It implements an `rpcwhitelist` of harmless rpc calls for services with rpc access (`clightning`, `lnd`, `liquidd`, and `electrs`).
Right now, I transfer the HMAC's from the `/secrets` directory by replacing a placeholder inside `bitcoin.conf` via `sed` in the `systemd.services.bitcoind.preStart`. I'm not sure if this is the optimal solution.
Closes https://github.com/fort-nix/nix-bitcoin/issues/191
Closes https://github.com/fort-nix/nix-bitcoin/issues/183

RPC Whitelist

---

.travis.yml
examples/configuration.nix
modules/lightning-loop.nix
modules/lnd.nix
modules/modules.nix
modules/netns-isolation.nix
modules/presets/secure-node.nix
pkgs/default.nix
pkgs/lightning-loop/default.nix
pkgs/lightning-loop/get-sha256.sh
pkgs/netns-exec/src/main.c
pkgs/pinned.nix
test/scenarios/default.py
test/scenarios/withnetns.py
test/test.nix

This PR integrates lightning-loop in nix-bitcoin. Lightning Loop is a [Non-Custodial Off/On Chain Bridge](https://github.com/lightninglabs/loop). It can be used for improvised CoinSwaps that utilize the privacy properties of LN.
Details
-  Based on https://github.com/fort-nix/nix-bitcoin/pull/201.
-  For testing purposes it includes https://github.com/NixOS/nixpkgs/pull/89668 in 7d512a5. This can be removed as soon as https://github.com/NixOS/nixpkgs/pull/89668 is merged, and the pinned nixpkgs in 3cbb691 are bumped.
- AFAICT the datadir can't be specified for loopd, but because of `ReadWritePaths` it's created in `/var/lib/lnd/.loopd` with the right permissions, which is kind of what we want.
Tested with a succesful `loop out` tx …

Lightning loop

---

examples/configuration.nix
modules/backups.nix
modules/modules.nix
modules/presets/secure-node.nix
pkgs/generate-secrets/generate-secrets.sh
test/scenarios/default.py
test/scenarios/lib.py
test/scenarios/withnetns.py
test/test.nix

This PR introduces nix-bitcoin's own backups module which backups up all important files in `/var/lib` to `/var/lib/localBackups` (fetchable with `nixops scp`) or a remote target url once a day using duplicity. Backups are encrypted with an apg generated password. A user can also backup the blockchains and electrs data directory with `cfg.with-bulk-data` (off-by-default).
The idea is to create a generic `backups.nix` module, which at first has duplicity support but supports extending to a variety of backup programs like restic, git-annex and borg.
Closes https://github.com/fort-nix/nix-bitcoin/issues/167

backups: add module

---

.travis.yml
examples/configuration.nix
modules/backups.nix
modules/btcpayserver.nix
modules/lnd.nix
modules/modules.nix
modules/netns-isolation.nix
modules/nodeinfo.nix
modules/presets/secure-node.nix
pkgs/btcpayserver/default.nix
pkgs/btcpayserver/deps.nix
pkgs/btcpayserver/update.sh
pkgs/default.nix
pkgs/generate-secrets/generate-secrets.sh
pkgs/nbxplorer/default.nix
pkgs/nbxplorer/deps.nix
pkgs/nbxplorer/update.sh
pkgs/nbxplorer/util/create-deps.sh
pkgs/nbxplorer/util/update-common.sh
pkgs/pinned.nix
test/base.py
test/scenarios/default.py
test/scenarios/withnetns.py
test/test.nix

Builds on https://github.com/fort-nix/nix-bitcoin/pull/220
Notes
* enforceTor is currently disabled for `systemd.services.btcpayserver` because BTCPayServer needs to fetch price rates from outside and doing this over Tor isn't supported yet. Maybe we need to implement a Tor transparent proxy and custom routing rules.
* I'm generating a custom macaroon with limited permissions à la https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/216a581f3296bfe37438f13def88a160a2f83509/lnd/gen_macaroons.sh#L34 and placing it inside `/var/lib/lnd/invoice+readonly.macaroon` because `/var/lib/lnd/chain/bitcoin/mainnet` is user-readable-only and I don't want to start changing folder permissions. Maybe there is a better place?
* I added a drive-by fix to `netns-isolation.nix` allowing return …

nbxplorer/btcpayserver: add module

---

modules/btcpayserver.nix

@Kukks mentioned on [Twitter](https://twitter.com/MrKukks/status/1305924746362654720) that using sqlite wasn't a good idea. Well, we're now using postgresql. I didn't put a lot of effort into automatic migration, as I don't think any user has deployed our btcpayserver module yet.

btcpayserver: sqlite -> postgresql

---

helper/push-release.sh

Add --dry-run option to push-release script

---

modules/lightning-charge.nix
modules/nanopos.nix

Fixes #233 
Because we have btcpayserver now, nanopos is not really needed any more. Nanopos
was meant to be just a PoC. Lightning charge can be removed because nanopos is
the only module that depends on it.

Deprecate lightning-charge and nanopos

---

.travis.yml
docs/usage.md
examples/configuration.nix
modules/backups.nix
modules/default.nix
modules/joinmarket.nix
modules/modules.nix
modules/netns-isolation.nix
modules/nix-bitcoin-services.nix
modules/presets/secure-node.nix
pkgs/default.nix
pkgs/generate-secrets/generate-secrets.sh
pkgs/joinmarket/bencoderpyx/default.nix
pkgs/joinmarket/chromalog/default.nix
pkgs/joinmarket/coincurve/default.nix
pkgs/joinmarket/default.nix
pkgs/joinmarket/genwallet/genwallet.py
pkgs/joinmarket/get-sha256.sh
pkgs/joinmarket/jmbase/default.nix
pkgs/joinmarket/jmbitcoin/default.nix
pkgs/joinmarket/jmclient/default.nix
pkgs/joinmarket/jmdaemon/default.nix
pkgs/joinmarket/python-bitcointx/default.nix
pkgs/joinmarket/python-bitcointx/get-sha256.sh
pkgs/joinmarket/secp256k1/default.nix
pkgs/joinmarket/urldecode/default.nix
pkgs/netns-exec/src/main.c
test/base.py
test/test.nix

This PR integrates JoinMarket into nix-bitcoin. All user scripts are created with `pkgs.writeScriptBin` and are executed in the `cfg.dataDir` with the right user and options. `tumbler.py` can be started in the background using GNU Screen. Yieldgenerator can be run as a systemd service.
How could I firewall the entire joinmarket user to only use Tor?
Thank you @erikarvstedt for your essential help throughout packaging this complex python program.
Closes https://github.com/fort-nix/nix-bitcoin/issues/32

Add JoinMarket Clientserver

---

pkgs/generate-secrets/default.nix

I accidentally included the minor version number.
Version 3.5 has been removed from nixpkgs unstable.
This helps fixing #241.

generate-secrets: fix python version for rpcauth

---

helper/push-release.sh

In a previous commit we found and replaced $1 with $TAG_NAME, but that wasn't
correct for the post_asset() function.

push-release: fix bug where assets are not pushed

---

modules/lightning-loop.nix
pkgs/generate-secrets/generate-secrets.sh
pkgs/generate-secrets/openssl.cnf
pkgs/lightning-loop/default.nix
test/base.py
test/test.nix

This PR updates the loop pkg. It also updates the module package to fully utilize the changes introduced in v0.9.0.
When we release this we need to include instructions, ideally a one-line command, to migrate existing loop directories from `/var/lib/lnd/.loop/ to `/var/lib/lightning-loop`.

loop: v0.8.1 -> v0.9.0

---

modules/bitcoind.nix
modules/clightning.nix
modules/hardware-wallets.nix
modules/joinmarket.nix
modules/liquid.nix
modules/lnd.nix
modules/modules.nix
modules/netns-isolation.nix
modules/nodeinfo.nix
modules/operator.nix
modules/presets/secure-node.nix
modules/spark-wallet.nix
test/run-tests.sh
test/tests.nix

This PR is based on [#243 Modularize Tests](https://github.com/fort-nix/nix-bitcoin/pull/243).
It fixes the tests for scenarios without secure-node.
The following is now working:
```
test/run-tests.sh -s full
test/run-tests.sh -s bitcoind
cat > /tmp/scenarios <<EOF
{...}: {
custom = {
services.electrs.enable = true;
services.lnd.enable = true;
};
}
EOF
scenarioOverridesFile=/tmp/scenarios test/run-tests.sh -s custom
```

Fix tests without secure-node

---

examples/configuration.nix
modules/modules.nix
modules/versioning.nix

This PR adds option `nix-bitcoin.configVersion` to inform users about backwards-incompatible changes and to provide migration hints.
A notification about the recent lightning-loop update could have been implemented like this:
```nix
{
version = "0.0.18";
condition = config.services.lightning-loop.enable;
message = ''
The lightning-loop data dir location was changed.
To move it to the new location, run the following shell command on your nix-bitcoin node:
sudo mv ${config.services.lnd.dataDir}/.loop ${config.services.lightning-loop.dataDir}
'';
}
```
To see it in action, checkout [this example branch](https://github.com/erikarvstedt/nix-bitcoin/commits/versioning-example) and run `test/run-tests.sh eval`
Example output:
```
This version of nix-bitcoin contains the following changes
that …
```

Add module 'versioning'

---

modules/bitcoind.nix
modules/btcpayserver.nix
modules/clightning.nix
modules/electrs.nix
modules/joinmarket.nix
modules/lightning-loop.nix
modules/lnd.nix
modules/netns-isolation.nix
modules/spark-wallet.nix
test/run-tests.sh
test/tests.nix
test/tests.py

Regtest allows testing services in a synced-blockchain scenario.
Run the test via `test/run-tests.sh -s regtest`.
Besides enabling in-depth service testing, this is also a great consistency check for our service modules. The number of service bugfixes included in this PR is testament to this.
`regtest` revealed that lightning-loop always requires `server.host` to be set. Should we add an option for it?

Add regtest support

---

examples/shell.nix

generate-secrets failed due to the `PYTHONPATH` env var that was set through the nixops19_09 buildInput.
Fixes:
- Don't pull in the build environments of binaries that should be available in `PATH`. Only extend `PATH` instead.
- Run generate-secrets in an empty environment
Fixes #253

shell.nix: fix failing generate-secrets

---

modules/lightning-loop.nix
pkgs/elementsd/default.nix
pkgs/lightning-loop/default.nix
pkgs/lightning-loop/get-sha256.sh
pkgs/spark-wallet/generate.sh
pkgs/spark-wallet/node-packages.nix
test/tests.py

Updates bringing spark-wallet, elementsd, and lightning-loop to their latest versions.
Closes https://github.com/fort-nix/nix-bitcoin/issues/248

nix-bitcoin pkg updates

---

examples/configuration.nix
modules/btcpayserver.nix
modules/clightning.nix
modules/electrs.nix
modules/joinmarket.nix
modules/lightning-charge.nix
modules/lightning-loop.nix
modules/liquid.nix
modules/lnd.nix
modules/nanopos.nix
modules/recurring-donations.nix
modules/spark-wallet.nix

Also, add missing dependencies to bitcoind, because `bitcoind.enable` is `false` outside of `secure-node.nix`.
Pros:
- Less code
- Adheres to the NixOS philosophy that services should automatically enable their dependencies
- Works like [cryptoanarchy-deb-repo-builder](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder), where, e.g., `sudo apt install btcpayserver` automatically installs all deps, including `lnd`.
- Enables auto-scenarios for all services, like `run-tests.sh -s btcpayserver` or `run-tests.sh -s spark-wallet`
Cons:
- The user might implicitly enable a lightning service and forget to back up its data. This is taken care of by the backup module.
Note that we can't use the following elegant definition in btcpayserver:
``` …
```

Services: Auto-enable dependencies

---

.travis.yml
modules/bitcoind.nix
modules/btcpayserver.nix
modules/clightning.nix
modules/electrs.nix
modules/joinmarket.nix
modules/lightning-loop.nix
modules/liquid.nix
modules/lnd.nix
modules/netns-isolation.nix
modules/presets/secure-node.nix
pkgs/netns-exec/src/main.c
test/run-tests.sh
test/tests.nix
test/tests.py

This is implemented by commits starting with `netns-bitcoind: allow RPC access from main netns`.
Pros:
- Much reduced implementation complexity: No extra CLI, no multiple service listen addresses.
- Improved usability: The `service.cli` binary will always work from all allowed namespaces, including the service's own netns.\
The previous CLI separation led to a bug in `regtestBase` because I inadvertently used `bitcoind.cli` instead of `bitcoind.cliBase` in `bitcoind.postStart` for generating regtest blocks.
Cons:
- Insignificantly decreased security for bitcoind and liquidd (not for lnd):\
Previously, attackers from the main netns had to pass the allowip and the rpcauth
checks to gain RPC access.\
Now, it's just rpcauth, like for connections from all other allowed netns.

Improve netns-isolation and Tor config

---

modules/netns-isolation.nix

This fixes netns service restarts on Travis, which were [broken in the test](https://github.com/fort-nix/nix-bitcoin/pull/258#issuecomment-721039403) for #256.
Because I didn't succeed in locally reproducing the error and because of Travis' long queue times, I couldn't determine the true cause of the error with certainty.
But empirically this patch seems to work: Here's the successful [CI test](https://travis-ci.org/github/erikarvstedt/nix-bitcoin/builds/741241894) with #256 applied on top of this PR.
We should merge this PR before #256.

Fix netns restart

---

modules/bitcoind.nix
modules/btcpayserver.nix
modules/clightning.nix
modules/electrs.nix
modules/hardware-wallets.nix
modules/joinmarket.nix
modules/lightning-charge.nix
modules/lightning-loop.nix
modules/liquid.nix
modules/lnd.nix
modules/modules.nix
modules/nanopos.nix
modules/netns-isolation.nix
modules/recurring-donations.nix
modules/secrets/generate-secrets.nix
modules/spark-wallet.nix
pkgs/default.nix

Nixpkgs 20.09 introduced a bug where nixpkgs overlays are ignored in containers. This breaks our `pkgs.nix-bitcoin` overlay:
```bash
$ test/run-tests.sh container
error: attribute 'nix-bitcoin' missing, at /home/main/d/nix-bitcoin/src/modules/bitcoind.nix:62:19
```
[My upstream bugfix PR](https://github.com/NixOS/nixpkgs/pull/98655) has not been merged yet.
Work around this by providing nix-bitcoin pkgs via an option instead of an overlay (in `modules.nix`).
This also has the advantage to slightly speed-up container builds because the `pkgs` of the host system can be reused in the container.

Fix containers for nixpkgs 20.09

---

test/lib/make-test-vm.nix

Since nixpks 20.09, the test output is just an empty directory.
Restore saving the log output and linking to the driver.
Without linking to the driver, the driver is eligible for garbage collection after running a test via `run-tests.sh --out-link-prefix`, which implies lengthy driver rebuilds.

testing framework: re-add features removed in nixpkgs 20.09

---

modules/lnd.nix

Setting `lnd.restPort` currently causes lnd not to start because it does not get written into the config. Probably introduced in de23fdd37780406c9b09e9f0528d8f7ae7cf1a76. Did not test with netns-isolation.

lnd: fix rpc/rest port configuration

---

examples/configuration.nix
modules/joinmarket.nix
modules/versioning.nix
pkgs/joinmarket/default.nix
pkgs/joinmarket/get-sha256.sh

This PR updates JoinMarket to 0.8.0 plus a hotfix for the genwallet script that I wrote myself. It includes a warning about the necessary migration steps. This warning isn't something for config versioning, right?
I had to temporarily change `get-sha256.sh` for the pinned commit. We can revert all this with version 0.8.1.

joinmarket: 0.7.4 -> 0.8.0-bcfa7eb

---

docs/faq.md
examples/configuration.nix
examples/deploy-qemu-vm.sh
modules/presets/hardened.nix
pkgs/extra-container/default.nix
pkgs/generate-secrets/default.nix
pkgs/generate-secrets/generate-secrets.sh
test/lib/make-container.sh
test/run-tests.sh
test/tests.nix

To compare the password output, run
```
nix run -f '<nixpkgs>' apg -c apg -m 20 -x 20 -M Ncl -n 1
nix run -f '<nixpkgs>' pwgen -c pwgen -s 20 1
```
Use this for auditing:
```
tmp=$(mktemp -d -p /tmp)
mkdir -p $tmp/{old,new}
fetchAndCheck() {
local url=https://github.com/erikarvstedt/extra-container/archive/$1.tar.gz
curl -sSL $url | tar xz --strip-components=1 -C $2;
echo "sha256 for $1 is $(nix hash-path --base32 "$2")"
}
fetchAndCheck 0.5-pre $tmp/old
fetchAndCheck 0.5     $tmp/new
git diff --no-index $tmp/{old,new}
rm -rf $tmp
```

Fix containers

---

modules/btcpayserver.nix

This PR adds the BTCPayServer rootpath option to our btcpayserver module. This allows you to set a custom root path like with `https://nixbitcoin.org/btcpayserver/`

btcpayserver: add rootpath option

---

modules/joinmarket.nix

`secrets.jm-wallet-password` is always needed by joinmarket, not just when `joinmarket.yieldgenerator.enable`

joinmarket: always synchronize secrets.jm-wallet-password

---

modules/joinmarket.nix

The [joinmarket docs](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#setting-a-core-wallet-recommended) recommend using a separate wallet to avoid mixing up jm and
default wallet.
In the future, ideally joinmarket would create the wallet by default, by using some kind of `wallet` option in the bitcoind module.

joinmarket: add rpcWalletFile option

---

modules/joinmarket.nix

Fix from 6af5238dfc6816568a3bf0c32285b5ccf012786f applied to `joinmarket` module.

joinmarket: add enforceTor to firewall scripts on netns-level

---

modules/nodeinfo.nix

```nodeinfo``` used ```lightning-cli``` for getting the pubkey.
Now the output is the pubkey as expected.

Fix lnd nodeinfo

---

pkgs/electrs/default.nix

This PR updates our electrs package. Eventhough this release [doesn't bring significant new features](https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md) I still think its good to keep up-to-date.

electrs: v0.8.6 -> v0.8.7

---

.cirrus.yml
ci/build-to-cachix.sh
examples/README.md
examples/configuration.nix
modules/bitcoind.nix
modules/onion-addresses.nix
modules/onion-services.nix
pkgs/nixpkgs-pinned.nix
pkgs/pinned.nix
test/pkgs-unstable.nix
test/run-tests.sh
test/tests.nix
test/tests.py

I couldn't reproduce #303, neither within our test framework nor on my production server.
Use the following for a live test of the new v3 onion service:
```
test/run-tests.sh -s '{
imports = [ <nix-bitcoin/modules/presets/secure-node.nix> ];
nix-bitcoin.onionServices.bitcoind.public = true;
test.container.enableWAN = true;
}' container
onionAddr=$(c nodeinfo | jq -r .bitcoind.onion_address | tr ':' ' ')
echo $onionAddr
torsocks nc -zv $onionAddr
c cat /var/lib/bitcoind/bitcoin.conf
c bitcoin-cli getnetworkinfo
```
Commit `improve backup test` fixes the cryptic `AssertionError` that probably happened to @nixbitcoin after updating nixpkgs-unstable.

Update nixpkgs-unstable, bitcoind

---

modules/bitcoind-rpc-public-whitelist.nix

It is needed by lnd to check bitcoind health status since version 0.12.0: https://github.com/lightningnetwork/lnd/pull/4755
If the api method is blocked lnd shuts down soon after starting.
```
...
Feb 02 22:13:30 nix-bitcoin bitcoind[8416]: 2021-02-02T21:13:30Z RPC User public not allowed to call method uptime
...
Feb 02 22:13:30 nix-bitcoin lnd[9845]: 2021-02-02 22:13:30.708 [CRT] SRVR: Health check: chain backend failed after 3 calls
Feb 02 22:13:30 nix-bitcoin lnd[9845]: 2021-02-02 22:13:30.708 [INF] SRVR: Sending request for shutdown
Feb 02 22:13:30 nix-bitcoin lnd[9845]: 2021-02-02 22:13:30.708 [INF] LTND: Received shutdown request.
Feb 02 22:13:30 nix-bitcoin lnd[9845]: 2021-02-02 22:13:30.708 [INF] LTND: Shutting down...
```

bitcoind: add uptime to the public API whitelist

---

test/lib/copy-src.sh

Previously, `run-tests.sh --copy-src ...` exited with status 0 (success) when interrupted (SIGINT).
It now exits with an error status.
For `ACK`ing PRs I'm using a shell command similar to this:
```
test/run-tests.sh --copy-src all && gh pr review $pr --approve --body "ACK $rev"
```
This was broken because `run-tests.sh` always succeeded on interrupts.

run-tests: Fix interrupt handling for --copy-src

---

modules/bitcoind.nix
modules/btcpayserver.nix
modules/electrs.nix
modules/lightning-loop.nix
modules/liquid.nix
modules/lnd-rest-onion-service.nix
modules/lnd.nix
modules/onion-addresses.nix
modules/onion-services.nix
modules/recurring-donations.nix
modules/spark-wallet.nix

This PR fixes an issue with LND reported by @mmilata in the Freenode `#nix-bitcoin` channel.
If both `nix-bitcoin.onionServices.lnd.public` & `services.lnd.restOnionService.enable` were enabled, one would try to create a file named `lnd` and the other would try to create a directory named `lnd` with a file named `lnd-rest` inside it. This would obiously cause an error and fail the LND service. 
A bit of a yak shave, but I had to use `${config.services.${service}.user}` in order to avoid the infinite recursion of `${config.systemd.services.${service}.serviceConfig.User}`.
I've tried my best to locate all uses of hardcoded usernames, but its not guaranteed that all have been found/fixed. Please double-check.

Fix lnd onion

---

modules/bitcoind.nix
modules/btcpayserver.nix
modules/clightning.nix
modules/electrs.nix
modules/liquid.nix
modules/lnd.nix
test/tests.py

This PR adds an option to enable bitcoind cookie-file based RPC authenticaiton. Programs like [revaultd](https://github.com/re-vault/revaultd/blob/25bb6922986709c642caec2f3ebb6cd750224c6f/src/common/config.rs#L13) only allow bitcoind cookie-file based RPC authentication. Users of these programs should be able to run them under the `bitcoin` user with cookie-file based RPC authentication.
Sadly this only allows `bitcoin` and `root` users to make `bitcoin-cli` calls without manually adding the `privileged` or `public` password.
EDIT: Feature requested by @danielabrozzoni

bitcoind: enable cookie-based authentication

---

README.md
examples/configuration.nix
modules/lightning-pool.nix
modules/modules.nix
modules/netns-isolation.nix
modules/presets/enable-tor.nix
pkgs/default.nix
pkgs/lightning-pool/default.nix
pkgs/lightning-pool/get-sha256.sh
test/pkgs-unstable.nix
test/tests.nix
test/tests.py

This PR integrates lightning-pool to nix-bitcoin. Lightning Pool is a non-custodial batched uniform clearing-price auction for Lightning Channel Leases (LCL). An LCL packages up inbound channel liquidity (ability to receive funds) as a fixed income asset with a maturity date expressed in blocks.
I'm pretty novice at nixos, so it's better if you take a closer look 😄 
Details
- The tls certificate and key can't be in the /secrets/ folder as the ```--basedir ``` arg overwrites ```--tlscertpath```
- The conf file needs to be written in the basedir folder, I don't know if the ```chmod``` and ```chown``` I did was right
- It requires the ```uptime``` bitcoind rpc call
- It requires a publicly reachable uri, I tried setting ```nix-bitcoin.onionServices.lnd.public=true;``` in the module itself, …

Lightning pool

---

pkgs/nixops/default.nix

Simple fix that doesn't force users to edit their `shell.nix`. AFAIK `libvirtd` is not currently needed in nix-bitcoin.
Fixes https://github.com/fort-nix/nix-bitcoin/issues/323

nixops: remove libvirtd plugin

---

examples/configuration.nix
modules/presets/hardened-extended.nix
pkgs/lib.nix
test/tests.nix

This PR implements a number of hardening measures from @madaidan's [Linux Hardening Guide](https://madaidans-insecurities.github.io/guides/linux-hardening.html).
It also replaces sudo with doas because of the recent CVE-2021-3156. Sudo is simply [too complex](https://lobste.rs/s/efsvqu/heap_based_buffer_overflow_sudo_cve_2021#c_c6fcfa) and includes features that a SETUID program should never have. Furthermore, it lets the operator user control selected services so we can discourage users from ssh'ing into the root user at all and instead recommend using the operator user for all normal system management tasks.
I have saved the remaining improvements from @madaidan's [Linux Hardening Guide](https://madaidans-insecurities.github.io/guides/linux-hardening.html), like system-wide AppArmor and …

Madaidan hardening

---

modules/clightning-plugins/clboss.nix
pkgs/clboss/default.nix
test/tests.nix

CLBOSS 0.10 pays an enormous amount in rebalancing fees, which appears to be fixed in CLBOSS 0.11A. It is only a pre-release and apparently has a bug [that prevents rebalancing](https://github.com/ZmnSCPxj/clboss/blob/master/ChangeLog). Hopefully we don't have to wait very long for a new release soon (ping @zmnscpxj :]). The new module option allowing custom packages will help users to run CLBOSS master or test specific PRs.

Update CLBOSS, add test, add option for custom pkg

---

README.md
examples/configuration.nix
modules/charge-lnd.nix
modules/default.nix
modules/modules.nix
modules/netns-isolation.nix
pkgs/pinned.nix
test/tests.nix
test/tests.py

Adds module for [charge-lnd](https://github.com/accumulator/charge-lnd), a tool for updating lnd channel fees based on list of rules.
~~The package is temporarily included for ease of testing as it has been submitted to nixpkgs unstable https://github.com/NixOS/nixpkgs/pull/124436. Marking this as a draft until then, early feedback appreciated though.~~
TODO:

charge-lnd: add module

---

pkgs/clightning-plugins/default.nix

This is necessary in preparation for clightning 0.10.1 which requires an update
to the rebalance plugin.
See [clightning release notes](https://github.com/ElementsProject/lightning/releases/tag/v0.10.1).

clightning-plugins: update to latest rev

---

modules/btcpayserver.nix
modules/liquid.nix
modules/netns-isolation.nix
pkgs/nixpkgs-pinned.nix
test/tests.nix
test/tests.py

Excuse the hackyness of pulling in a custom `nixpkgs-unstable` for the BTCPayServer Altcoin support. I'm working on patching it elegantly upstream.

BTCPayServer L-BTC Support

---

pkgs/extra-container/default.nix
test/lib/make-container.sh
test/run-tests.sh

There's no common `nix` command argument syntax for eval'ing a nix expression that supports both older and newer (flake support) versions of nix.
So fall back to nix-instantiate.

run-tests: Fix 'eval' command for newer versions of nix

---

examples/shell.nix
helper/makeShell.nix

This simplifies future shell upgrades.

examples/shell.nix: Add shell version variable

---

modules/backups.nix
modules/bitcoind.nix
modules/btcpayserver.nix
modules/charge-lnd.nix
modules/clightning-plugins/default.nix
modules/clightning-plugins/zmq.nix
modules/clightning.nix
modules/electrs.nix
modules/hardware-wallets.nix
modules/joinmarket-ob-watcher.nix
modules/joinmarket.nix
modules/lightning-loop.nix
modules/lightning-pool.nix
modules/liquid.nix
modules/lnd-rest-onion-service.nix
modules/lnd.nix
modules/netns-isolation.nix
modules/nodeinfo.nix
modules/onion-addresses.nix
modules/onion-services.nix
modules/operator.nix
modules/recurring-donations.nix
modules/spark-wallet.nix
modules/versioning.nix

All commits are non-functional and have no effect on system derivations.
You can test this by evaluating the default test VM: `test/run-tests.sh eval`
This commit was auto-generated by a script.
Use [this script](https://gist.github.com/293c3054e2df949a7258ecd40b824938) to verify this.
Check the following files to see the advantages of the new formatting:
`joinmarket.nix`: [old](https://github.com/fort-nix/nix-bitcoin/blob/cf70d05be0fe8f2b97380931125cac92e0373557/modules/joinmarket.nix), [new](https://github.com/erikarvstedt/nix-bitcoin/blob/f6b219de50c42a8891c2749238583469f0730d4c/modules/joinmarket.nix)
`bitcoind.nix`: [old](https://github.com/fort-nix/nix-bitcoin/blob/cf70d05be0fe8f2b97380931125cac92e0373557/modules/bitcoind.nix), …

Modules formatting

---

examples/configuration.nix
modules/presets/secure-node.nix
modules/versioning.nix

There is no security reason why pruning should be enabled and therefore it
surprises users. Turning on pruning in the first place was simply a mistake.
Fixes #413

secure-node: stop pruning liquidd

---

modules/nodeinfo.nix

- fix missing import utilized here: https://github.com/fort-nix/nix-bitcoin/blob/master/modules/nodeinfo.nix#L71

missing sys import for error path set_onion_address

---

pkgs/cl-rest/generate.sh
pkgs/cl-rest/node-packages.nix

Unsigned NPM packages and hot wallet funds don't go together very well. Anyone of the myriad of dependencies could be backdoored on every update. Should we expose users to these risks? We can't review all these changes.

cl-rest: 0.5.2 -> 0.6.0

---

test/run-tests.sh

Previously, `qemu` failed with error `restrict=on : Parameter 'restrict' expects 'on' or 'off'` due to the trailing space after `on`.

run-tests: fix `vm` cmd

---

helper/makeShell.nix

This fixes a bug where the version update message for v0.0.65 is erroneously triggered because the krops config is not included when evaluating secrets.

makeShell: use final system configuration in generate-secrets

---

README.md
examples/configuration.nix

I think it is not clearly apparent to new users that we support LND Static Channel Backups out of the box. Especially in conjunction with our `backups` module, this provides a fairly basic recovery strategy for LND.
At least a partial answer to https://github.com/fort-nix/nix-bitcoin/issues/409

lnd: point out SCB functionality more clearly

---

modules/liquid.nix
pkgs/default.nix

Previously, liquidd could fail with error:
`liquidd.service: start operation timed out. Terminating.`

liquidd: add service timeouts like in bitcoind

---

pkgs/default.nix
pkgs/secp256k1/default.nix

Also incorporate improvements from upstream nixpkgs expression.
GPG verified upstream commit and repo checksum.

joinmarket: bump secp256k1 to version used upstream

---

modules/secrets/secrets.nix

With newer nixpkgs versions, a type error was shown instead of the warning message when `secretsSetupMethod` was unset.
Reproduce with:
```bash
nix eval --impure --expr '
(import <nixpkgs/nixos> {
configuration = {
imports = [
<nix-bitcoin/modules/modules.nix>
];
};
}).system
'
```

secrets: fix secrets setup warning

---

modules/joinmarket.nix
pkgs/joinmarket/default.nix
pkgs/python-packages/python-bitcointx/default.nix
pkgs/python-packages/python-bitcointx/get-sha256.sh
test/tests.nix
test/tests.py

Notes
- We can no longer test for `unknown error in JSON-RPC`. `jm-ob-watcher`
now simply outputs `Starting ob-watcher`. Tested working on
https://nixbitcoin.org/orderbook.
- Removed Agora IRC server since it is offline semi-permanently. Should
probably also be removed upstream.
- Includes patch for
https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1193

joinmarket: 0.9.4 -> 0.9.5

---

modules/bitcoind.nix
modules/btcpayserver.nix
modules/clightning-rest.nix
modules/clightning.nix
modules/electrs.nix
modules/joinmarket.nix
modules/lightning-loop.nix
modules/lightning-pool.nix
modules/liquid.nix
modules/lnd.nix
modules/rtl.nix
pkgs/lib.nix

This makes our list definitions mergeable with custom list values set by users.
Previously, a module error ("value is a string while a list was expected") was thrown instead.
This commit was partly auto-generated with this script:
```ruby
#!/usr/bin/env ruby
Dir["**/*.nix"].each do |file|
src = File.read(file)
fixed = src.gsub(/ReadWritePaths *= *(.*?);/) do
"ReadWritePaths = [ #{$1} ];"
end
File.write(file, fixed) if fixed != src
end
```

services: set systemd list options as list values

---

pkgs/default.nix

Previously, `builtins.defaultSystem` was implicitly used.
This fixes NixOS system builds for systems other than `defaultSystem`. 
(Flake-based systems are unaffected.)
Fixes #482

pkgs-unstable: inherit system from stable pkgs

---

modules/bitcoind.nix
modules/liquid.nix

I've just seen `liquidd` hit the timeout on nixbitcoin.org while `Loading block index`.
This was probably due to HDD contention while starting services during
boot.

bitcoind, liquidd: increase `TimeoutStartSec`

---

modules/nodeinfo.nix

Module authors can now add extra services via option `nix-bitcoin.nodeinfo.services`.
Mark as internal because we're not yet providing a user-friendly, stable API.
Test this with:
```
read -d '' config <<'EOF' || :
{ config, ... }: {
options = {
services.myservice.enable = mkOption { default = true; };
};
config = {
services.electrs.enable = true;
services.clightning.enable = true;
nix-bitcoin.nodeinfo = {
enable = true;
services = {
myservice = _: _: ''
infos["myservice"] = "example output"
'';
};
};
};
}
EOF
run-tests.sh -s "$config" container --run c nodeinfo
```

nodeinfo: make extensible

---

modules/presets/bitcoind-remote.nix

I think there is a small typo in quotation marks.

bitcoind-remote: fix quotation marks in preStart script

---

docs/configuration.md

clightning and lnd services should be allowed to connect to a remote bitcoind daemon

clightning/lnd: allow connections to remote bitcoind in systemd service

---

docs/install.md
flake.nix
helper/makeShell.nix

Most importantly, this unlocks `deploy` on macOS.
Use the following for testing:
```bash
cd /path/to/nix-bitcoin
cd examples
sed -i -r 's|#(./hardware-configuration.nix)|\1|' configuration.nix
echo '
{
boot.isContainer = true;
documentation.enable = false;
}
' > hardware-configuration.nix
rm -f krops/system
nix-shell --run eval-config
OSTYPE=darwin19 nix-shell --run eval-config
echo "aarch64-linux" > krops/system
OSTYPE=darwin19 nix-shell --run eval-config
echo "x86_64-linux" > krops/system
nix-shell --run build-config
```
This PR requires a special mention in the release notes.
I'll post the text here when this is merged.

krops: Enable evaluating nodes with non-native systems

---

modules/secrets/secrets.nix

Now the bash globbing sort order equals the nix sort order (order of `processedFiles`)
Previously, `comm` could fail with error `unsorted` on specific secrets names.

secrets: fix sorting in `setup-secrets`

---

examples/deploy-krops.sh

Previously, `deploy-krops.sh` failed when run in a freshly cloned repo due to missing secrets.

examples/deploy-krops: fix missing secrets

---

modules/operator.nix
test/nixos-search/ci-test.sh

Fix error `Invalid XML` when running flake-info (nixos-search).

operator: fix syntax error in description

---

README.md
modules/clightning-plugins/default.nix
pkgs/clightning-plugins/default.nix

clightning: add currencyrate plugin
Add the currencyrate plugin. This is used by other plugins to fetch
currency rates. This can be used for setting fiat amounts in bolt12
invoices.

clightning: add currencyrate plugin

---

modules/bitcoind.nix
modules/onion-services.nix

Currently, public services that publish their onion addresses have a `requires` dependeny on service `onion-addresses`, so they are restarted when `onion-addresses` restarts.
This has the downside that most of nix-bitcoin's services are restarted when a new onion service is added and the system config has the following common settings:
- nix-bitcoin.onionServices.bitcoind.public = true
- nix-bitcoin.operator.enable = true
Sequence of events:
1. onion service is added
2. `onion-addresses` restarts, because the new onion service is made available to `operator`
3. bitcoind restarts
4. all depending services restart
Fix this by using a `wants` dependency.

onion-services: don't propagate restart of `onion-addresses` to depending services

---

README.md
docs/services.md
modules/clightning-replication.nix
modules/clightning.nix
modules/modules.nix
pkgs/default.nix
test/clightning-replication.nix
test/lib/make-test.nix
test/run-tests.sh
test/tests.nix
test/tests.py

Not ready for merge until clightning 0.10.3.
Supersedes https://github.com/fort-nix/nix-bitcoin/pull/415
Coauthor: @erikarvstedt

clightning: native database replication

---

.cirrus.yml
examples/deploy-container-minimal.sh
examples/deploy-container.sh
examples/deploy-krops.sh
examples/deploy-qemu-vm.sh
examples/qemu-vm/run-vm.sh
examples/start-bash-session.sh
helper/fetch-release
helper/push-release.sh
helper/update-fixed-output-derivation.sh
pkgs/clightning-plugins/get-sha256.sh
pkgs/clightning-rest/generate.sh
pkgs/joinmarket/get-sha256.sh
pkgs/krops/fetch-release.sh
pkgs/lndinit/get-sha256.sh
pkgs/python-packages/python-bitcointx/get-sha256.sh
pkgs/rtl/generate.sh
pkgs/spark-wallet/generate.sh
test/ci/build-to-cachix.sh
test/ci/build.sh
test/lib/copy-src.sh
test/lib/create-git-repo.sh
test/lib/make-container.sh
test/lib/make-test-vm.nix
test/nixos-search/ci-test.sh
test/run-tests.sh
test/shellcheck.sh

This PR adds shellcheck lint to helper bash scripts, for more info please see:
- https://github.com/fort-nix/nix-bitcoin/issues/528

ShellCheck for various helper bash scripts

---

.cirrus.yml
README.md
test/run-tests.sh

The nixos-search binary currently fails with:
```
Error: Getting flake info caused an error: Failed to analyze flake ../..
Caused by:
0: [22]: data did not match any variant of untagged enum FlakeEntry at line 1 column 11194
1: data did not match any variant of untagged enum FlakeEntry at line 1 column 11194
```
This happens locally and in [CI](https://github.com/erikarvstedt/nix-bitcoin/runs/8193778511).
The [NixOS option search](https://search.nixos.org/flakes?channel=unstable&from=0&size=30&sort=relevance&type=options&query=mail) also has stopped showing results (for all queries).
The error doesn't happen when run in a firejail container with `--net=none`. I currently don't have time for further debugging.

tests: disable `nixosSearch`

---

test/lib/create-git-repo.sh

Remove quotes around var that may expand to nothing.

test/lib/create-git-repo: fix variable quoting

---

modules/lnd.nix
test/lib/shellcheck-services.nix
test/run-tests.sh
test/tests.nix

This branch includes some required commits from #559.
I've confirmed that lnd requires extra bitcoin RPC commands (via [pruned_block_dispatcher.go](https://github.com/btcsuite/btcwallet/blob/master/chain/pruned_block_dispatcher.go)) when bitcoind is pruned. This PR fixes the missing RPC permissions.
@ekimber, does this PR fix #562 for you?

lnd: fix missing RPC permissions when bitcoind is pruned

---

modules/bitcoind.nix

Previously, dhcpcd and bitcoind starting up in parallel could lead to the following error in bitcoind:
```
bitcoind: libevent: getaddrinfo: address family for nodename not supported
bitcoind: Binding RPC on address 127.0.0.1 port 8332 failed.
bitcoind: Unable to bind any endpoint for
```
After the initial failure, the bitcoind service would always restart successfully.
This race condition, where both applications were simultaneously manipulating network resources, was only triggered under specific hardware conditions.
Fix it by running bitcoind after dhcp has started (by running after `network-online.target`).
This bug and the fix only affect the default NixOS scripted networking backend.
Upstream fix in nixpkgs: https://github.com/NixOS/nixpkgs/pull/199147

bitcoind: fix rare startup error

---

modules/bitcoind.nix
modules/clightning.nix
modules/lightning-loop.nix
modules/lightning-pool.nix
modules/liquid.nix
modules/lnd.nix
modules/nix-bitcoin.nix

These scripts previously failed when called with syscalls like `execve` (used by, e.g., Python's `subprocess.run`) that use no default interpreter for scripts without a shebang.

treewide: set shebang for bash scripts

---

modules/lnd.nix

Use the following for manual testing. lnd currently doesn't support IPv6 zmq sockets (but bitcoind does), so only test IPv4 here:
```bash
run-tests.sh -s '{
services.lnd.enable = true;
services.bitcoind = {
zmqpubrawblock = "tcp://0.0.0.0:12345";
zmqpubrawtx =  "tcp://0.0.0.0:12346";
};
}' container --run c bash -c 'cat /var/lib/lnd/lnd.conf && systemctl status lnd'
```

lnd: support `INADDR_ANY` addresses for `bitcoind.zmqpubraw*`

---

README.md
dev/README.md
dev/dev-env/create.sh
dev/dev-env/dev-shell.nix
dev/dev-env/nix-bitcoin-firejail.conf
dev/dev-env/template-scenarios.nix
dev/dev-features.sh
dev/dev-scenarios.nix
dev/dev.sh
dev/topics/rtl.sh
docs/configuration.md
examples/README.md
flake.nix
test/README.md
test/run-tests.sh
test/tests.nix

Add dev helper and docs

---

.cirrus.yml
README.md
docs/services.md
modules/clightning-plugins/default.nix
modules/clightning-plugins/trustedcoin.nix
modules/clightning.nix
pkgs/default.nix
pkgs/trustedcoin/default.nix
pkgs/trustedcoin/get-sha256.sh
test/tests.nix
test/tests.py

This PR tries to add a trustedcoin support into the nix-bitcoin.
The work is based on PRs:
- https://github.com/fort-nix/nix-bitcoin/pull/533 
- https://github.com/fort-nix/nix-bitcoin/pull/583
The code is rebased on current master.
I have removed the `clightning.useBcli` option and replaced it with `clightning.useBitcoind`. When setting this option to `true`, the bitcoind unit is forcerly disabled and `clightning.plugins.trustedcoin.enabled` is set to `true` as suggested in https://github.com/fort-nix/nix-bitcoin/pull/533#issuecomment-1229428074.
I also tried to add some basic tests.
@erikarvstedt , could you please take a look and give me some suggestions? Please keep in mind this is only a draft but I would like to move this feature forward.
Thanks!
CC: @neverupdate , @MatthewCroughan …

Integrate trustedcoin clightning plugin

---

pkgs/lnd/default.nix

Currently, updating https://github.com/lightningnetwork/lnd/pull/7672 would break our patched `lnd` because the patch URL is not content-addressed.
After this is merged, we should make another release.
Sorry for the mishap.

lnd: fix non-static patch URL

---

modules/presets/secure-node.nix

A convenience helper which allows running most `sudo` cmds while `doas` is enabled.
This is safe because all args supported by both `sudo` and `doas` that lead to command execution (like `-u <user>`) have identical semantics.

secure-node: add `sudo` shell alias for `doas`

---

examples/flakes/flake.nix
helper/push-release.sh

`push-release` now pushes to an extra branch named `nixos-<VERSION>`, alongside branch `release`.
This allows users to track a specific NixOS release, so that their config doesn't break when nix-bitcoin switches to a new NixOS release.

Add versioned release branches

---

dev/dev-features.sh
docs/services.md
modules/joinmarket.nix
modules/lightning-loop.nix
modules/lightning-pool.nix
modules/lnd.nix
test/tests.nix

lnd and lightning-loop resolve `localhost` to an IPv4 address when creating RPC sockets.
Since NixOS 23.05, RTL (nodejs) resolves `localhost` to an IPv6 address when connecting to lnd and lightning-loop, which leads to connection errors.
To fix these and other potential errors, replace all instances of `localhost` with `127.0.0.1`.

rtl: fix lnd, lightning-loop connection errors

---

docs/install.md

[Rendered doc](https://github.com/erikarvstedt/nix-bitcoin/blob/fix-install-docs/docs/install.md#3-setup-deployment-directory).
1. This simplifies the setup
2. Fixes a bug where a user skipped step 4.6 (run `nix-shell`) which he deemed superfluous because a Nix shell was already active.
This caused an error during deployment.

docs/install: don't enter examples shell while creating node config

---

modules/clightning.nix

Use this to test commit `clightning: don't cleanup socket on startup`:
```bash
read -rd '' script <<'EOF' || :
systemctl stop clightning
echo
echo 'clightning has stopped'
systemctl status clightning | head -3
echo
echo 'the socket still exists after clightning has stopped'
ls /var/lib/clightning/bitcoin/lightning-rpc
echo
systemctl start clightning
echo 'clightning starts, rpc calls work'
sleep 0.5
lightning-cli getinfo
EOF
run-tests.sh -s clightning container --run c bash -c "$script"
```

Minor clightning fixes

---

pkgs/default.nix

All deps required by `bitcoind` are available in `pkgs`.

pkgs/bitcoind: use `pkgs` instead of `pkgsUnstable`

---

modules/backups.nix
modules/btcpayserver.nix
modules/clightning.nix
modules/electrs.nix
modules/fulcrum.nix
modules/joinmarket-ob-watcher.nix
modules/joinmarket.nix
modules/lightning-loop.nix
modules/liquid.nix
modules/lnd.nix
modules/rtl.nix

Now all services that access secrets only run after the secrets setup has finished.
Previously, we assumed that the systemd `after` dependency is transitive, i.e. that adding an `after = [ "bitcoind.service" ]` to a service implicitly pulled in the `after` dependency to `nix-bitcoin-secrets.target` (which is defined for `bitcoind`).
This is not the case. Services could start before secrets setup had finished, leading to service failure.

treewide: ensure services are started after secrets setup

---

modules/clightning.nix

Also, add a detailed comment.
Without this commit, clightning client services may fail to start because of clightning RPC connection failures. This can happen unnoticed due to the service auto restart mechanism.

Revert "clightning: don't cleanup socket on startup"

---

modules/presets/wireguard.nix

Disable Tor enforcement set by the secure-node preset.

presets/wireguard: make compatible with `secure-node` preset

---

pkgs/clboss/default.nix

If I use the latest nixpkgs-unstable, i get this error when enabling clboss:
```
$ sudo nixos-rebuild switch 
building the system configuration...
error:
… while calling the 'head' builtin
at /nix/store/mj0hy52z22q5gpsf33akndxiclxd8ray-source/lib/attrsets.nix:850:11:
849|         || pred here (elemAt values 1) (head values) then
850|           head values
|           ^
851|         else
… while evaluating the attribute 'value'
at /nix/store/mj0hy52z22q5gpsf33akndxiclxd8ray-source/lib/modules.nix:807:9:
806|     in warnDeprecation opt //
807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
|         ^
808|         inherit (res.defsFinal') highestPrio;
(stack trace truncated; use '--show-trace' to show the full trace)
error: 'pkgconfig' has …
```

fix pkgconfig -> pkg-config rename

---

docs/install.md

"Migrating existing services to bitcoind" at the bottom of nix-bitcoin/docs/install.md should read "Migrating existing services to nix-bitcoin" since it links to the section of configuration.md called "Migrate existing services to nix-bitcoin"

Docs: fix small error in installation.md

---

test/tests.nix

Due to the slowdown caused by the hardening features, the `hardened` test occasionally failed since the upgrade to NixOS 23.11.
Error:
```
vm-test-run-nix-bitcoin-hardened> machine # [  147.136056] lightningd[1667]: UNUSUAL plugin-cl-zmq.py: Killing plugin: timed out before replying to getmanifest
vm-test-run-nix-bitcoin-hardened> machine # [  147.151591] lightningd[1667]: UNUSUAL plugin-cl-zmq.py: Killing plugin: Invalid/missing result tok in '{"jsonrpc": "2.0","id": 16,"error": {"code":-4, "message":"Plugin terminated before replying to RPC call."}}'
vm-test-run-nix-bitcoin-hardened> machine # [  147.152555] lightningd[1667]: Can't recover from plugin failure, terminating.`
```

tests/hardened: fix test for slower hardware

---

flake.nix
test/tests.nix

By using the `default` flake module for tests, `pkgsUnstable` in `pkgs/default.nix` gets passed the `nixpkgs-unstable` flake input instead of falling back to importing `nixpkgsPinned.nixpkgs-unstable`.
For some use cases this prevents importing `nixpkgs-unstable` twice (once via the `nixpkgs-unstable` flake input, once via `import nixpkgsPinned.nixpkgs-unstable`).

test: use `nixpkgs-unstable` flake input for nix-bitcoin pkgs

---

examples/README.md
examples/container/flake.nix
examples/container/usage.sh
test/run-tests.sh

This is also helpful for users who want to run an extra testnet/regtest node on a nix-bitcoin system.

examples: add persistent container example

---

pkgs/clboss/default.nix

Opening new channels, the main feature of clboss, was broken with clightning v24.02 + clboss 0.13:
https://github.com/ZmnSCPxj/clboss/issues/189

clboss: 0.13 -> 0.13.1

---

pkgs/joinmarket/default.nix

Closes #693 
Include the [bond-calculator.py](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/scripts/bond-calculator.py) script into joinmarket's CLI commands.

joinmarket: include the bond-calculator script

---

pkgs/trustedcoin/default.nix

There is a new release of trustedcoin:
- https://github.com/nbd-wtf/trustedcoin/releases/tag/v0.7.0

trustedcoin: 0.6.1 -> 0.7.0

---

pkgs/python-packages/python-bitcointx/default.nix
test/tests.nix

Now substitution failures result in a script error.
This has recently been backported to nixpkgs 23.11.

treewide: use `substituteInPlace --replace-fail`

---

modules/bitcoind-rpc-public-whitelist.nix

Required by lnd 0.18.0.
The bug fixed here can only be reproduced on a fully-synced mainnet/testnet node.
lnd error:
```
[ERR] LNWL: Encountered err while fetching fee filters: status code: 403, response: ""
```

bitcoind-rpc-public-whitelist: add `getpeerinfo`

---

README.md

There's 3-4 people and one of them is me. There hasn't been actual discussion in months.
Would be also nice to put link to the matrix channel in the topic but that would probably require assistance from libera.chat or nix people who own the `#nix-` prefix?

README: don't mention IRC channel which is now unused

---

modules/bitcoind-rpc-public-whitelist.nix
modules/bitcoind.nix
modules/btcpayserver.nix
modules/lnd.nix

bitcoind-rpc-public-whitelist: Add `getnodeaddresses`

---

docs/services.md
modules/joinmarket-ob-watcher.nix
modules/joinmarket.nix
modules/obsolete-options.nix
pkgs/joinmarket/default.nix
test/tests.nix

Joinmarket settings can now be freely specified:
```nix
services.joinmarket = {
enable = true;
settings = {
POLICY = {
merge_algorithm = "gradual";
tx_fees = 5;
};
LOGGING = {
console_log_level = "DEBUG";
};
};
};
```
Closes #707
The updated `joinmarket-ob-watcher` is deployed at https://nixbitcoin.org and is working fine.
@seberm, can you help reviewing and testing this?

joinmarket: Add option `settings`

---

modules/lnd.nix

By wrapping the value in a list, users can add other `ExecStartPost` scripts.
The previous scalar value could only be replaced, but not merged with other definitions.
```bash
run-tests.sh -s '{
services.lnd.enable = true;
systemd.services.lnd.serviceConfig.ExecStartPost = lib.mkAfter [ "${pkgs.hello}/bin/hello" ];
}' container --run c journalctl -u lnd
```
Result:
```
...
Nov 06 16:51:05 nb-test lnd[533]: 2024-11-06 16:51:05.096 [INF] LTND: Waiting for chain backend to finish sync, start_height=0
Nov 06 16:51:05 nb-test hello[545]: Hello, world!
Nov 06 16:51:05 nb-test systemd[1]: Started lnd.service.
```

lnd: make `ExecStartPost` extensible

---

README.md
dev/dev-scenarios.nix
dev/topics/lndconnect-and-wireguard.sh
dev/topics/rtl.sh
docs/services.md
examples/configuration.nix
modules/clightning-plugins/clnrest.nix
modules/clightning-plugins/default.nix
modules/lndconnect.nix
modules/mempool.nix
modules/netns-isolation.nix
modules/nodeinfo.nix
modules/presets/wireguard.nix
modules/rtl.nix
pkgs/lib.nix
pkgs/python-packages/clnrest/default.nix
pkgs/python-packages/default.nix
pkgs/rtl/default.nix
pkgs/rtl/generate.sh
test/tests.nix
test/tests.py
test/wireguard-lndconnect.nix

This fixes `lndconnect` for recent versions of Zeus
Todo:

rtl: 0.14.1 -> 0.15.4, add `clightning.plugins.clnrest`

---

.cirrus.yml
dev/README.md
examples/configuration.nix
examples/flakes/flake.nix
flake.lock
flake.nix
helper/update-flake.sh
modules/btcpayserver.nix
modules/netns-isolation.nix
pkgs/pinned.nix
pkgs/python-packages/clnrest/default.nix
pkgs/python-packages/joinmarket/default.nix
pkgs/python-packages/pyln-proto/default.nix
test/clightning-replication.nix
test/lib/extra-container-check-version.sh
test/tests.py

Update to NixOS 24.11

---

examples/container/flake.nix

Some of the commands listed in `usage.sh` require clightning to be enabled. This commit enables clightning so they will work.

container example: add clightning to flake, remove electrs

---

examples/container/flake.nix
examples/container/usage.sh

This test requires `electrs` to be enabled.
Also, by using `electrs` instead of `clightning` we avoid the bug where clightning hangs at startup when internet access is unavailable. Due to technical limititations, internet access is available in NixOS containers only after the container has started.

Fix test `persistentContainerExample`

---

dev/README.md
examples/container/flake.nix
helper/update-flake.sh

Use the `update-flake.sh` script to auto-update the NixOS version at various places.
Also update `examples/container/flake.nix` which has been missing in the update instructions.

dev: add more automation to NixOS version updates

---

modules/btcpayserver.nix
modules/clightning-rest.nix
modules/fulcrum.nix
modules/liquid.nix
modules/mempool.nix
modules/rtl.nix
test/tests.py

Let A be a service that depends on another service B.
When A can gracefully handle failures and restarts of B, use
```
wants = [ "B.service" ];
after = [ "B.service" ];
```
instead of
```
requires = [ "B.service" ];
after = [ "B.service" ];
```
in the definition of A.
This way, A keeps running when B is stopped or restarted after a failure.
With `requires`, A is instead stopped when B is stopped or restarted due to a failure.
This brings two benefits:
1. Improved uptime
Examples:
- RTL keeps running when one lightning node has failed
- btcpayserver keeps running and accepting on-chain payments when the lightning node has crashed
2. Avoids a systemd bug where depending units (`A.service` in the above example) are not restarted when their dependency fails
(issue github/systemd#18856, no …

services: use `wants` dependency where possible

---

modules/bitcoind-rpc-public-whitelist.nix

This is used by nbxplorer since v2.5.24 on pruned nodes:
https://github.com/dgarage/NBXplorer/pull/511

bitcoind-rpc-public-whitelist: add `getblockfrompeer`

---

pkgs/trustedcoin/default.nix

https://github.com/nbd-wtf/trustedcoin/releases/tag/v0.8.4
Test with:
```bash
run-tests.sh -s trustedcoin
```

trustedcoin: 2024-11-15 -> 0.8.4

---

modules/bitcoind.nix

The upper limit has been removed.
See item `The maximum allowed value...` at https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-29.0.md#updated-settings
Test with
```bash
run-tests.sh -s '{ services.bitcoind.dbCache = 0; }' eval
run-tests.sh -s '{ services.bitcoind.dbCache = 4; }' eval
```

bitcoind: remove upper limit of option `dbcache`

---

examples/configuration.nix

Explicitly import modules.nix, so that users can remove the secure-node.nix import.
Fixes #804

examples/configuration.nix: Improve `secure-node` preset documentation

---

pkgs/trustedcoin/default.nix

https://github.com/nbd-wtf/trustedcoin/releases/tag/v0.8.5
https://github.com/nbd-wtf/trustedcoin/releases/tag/v0.8.6

trustedcoin: 0.8.4 -> 0.8.6
